config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root to: 'static_pages#home', :via => [:get, :post]
  
  match '/signup', to: 'users#new', :via => [:get, :post]

  match '/help', to: 'static_pages#help', :via => [:get, :post]
  
  match '/about', to: 'static_pages#about', :via => [:get, :post]
  
  match '/contact', to: 'static_pages#contact', :via => [:get, :post]

  resources :users

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
# id :integer not null, primary key
# name :string(255)
# email :string(255)
# created_at :datetime
# updated_at :datetime
#

class User < ActiveRecord::Base
	has_secure_password
	
	before_save{ |user| user.email = email.downcase}
	
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	validates :password, presence: true, length: { minimum: 6 }
	validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def user_params
	params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "Shopping Cart"
		if page_title.empty?
		base_title
		else
		"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://railstutorial.org/">Ruby App</a>
		by Insert Name Here
	</small>
	<nav>
		<ul>
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "Contact", contact_path %></li>
		<li><a href="http://io9.com">Geeky Stuff</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-custom navbar-fixed-top">
  <div class="container-fluid">
	<div class="navbar-header">
	  <%= link_to "Shopping Cart", '#', id: "logo" %>
	</div>
	<div>
	  <ul class="nav navbar-nav">
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "Help", help_path %></li>
		<li><%= link_to "Sign in", '#' %></li>
	  </ul>
	</div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag "application", media: "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
		<style>
			a:hover {
				color: #000;
				background-color: transparent;
				text-decoration: none;
			}
		</style>
		<%= render 'layouts/header' %>
		<div class="container">
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>
	The <a href="http://railstutorial.org/">site</a>
	is a project under sir Francis's CS112 Programming Language class. This
	is the 5th homework which enables us to learn Ruby concepts.
	</p>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
	Contact us <a href="http://facebook.com">here</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
	Get help on this Shopping Cart Help at the
	<a href="http://railstutorial.org/help">this page page</a>.
	To get help on this application, see
	<a href="http://railstutorial.org/book">this one</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<h1>Shopping Cart</h1>
	
	<h2>
		This is the home page for the
		<a href="http://railstutorial.org/">Shopping Cart</a>
		...or whatever.
	</h2>
	
	<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-custom" %>
	
	<p>
	</p>
	
	<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>Waley pa ahehehe.</p>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>